### ISSUE TITLE
If I serve the page locally with "jekyll serve", it shows a directory listing

### ISSUE THREAD

**Issue by bast** [orchid00/The_Carpentries_info#2]
Are you able to serve the page locally (for preview)?

**Comment by orchid00** [comment]
hi @bast, 

> Are you able to serve the page locally (for preview)?

not with jekyll, I can preview using atom.
If you want to `jekyll serve` I guess you need to add a Gemfile.

This repo is using a theme from github, so all the build is happening on the server directly.

**Comment by bast** [comment]
Thanks! OK I arrived with a different workflow but it's good to know and in my opinion not something that needs to be changed, was just wondering how you preview changes and using Atom is a nice alternative I did not think about.
